# Generated by Django 6.0.4 on 2026-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='upgrade_cost',
            field=models.IntegerField(default=10),
        ),
    ]
