# Generated by Django 6.0.4 on 2026-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_upgrade_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='auto_upgrade_cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='points_per_second',
            field=models.IntegerField(default=0),
        ),
    ]
