# Generated by Django 6.0.4 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_auto_upgrade_cost_player_points_per_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='crit_chance',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='player',
            name='crit_multiplier',
            field=models.FloatField(default=2.0),
        ),
    ]
