# Generated by Django 6.0.4 on 2026-04-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_crit_chance_player_crit_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='crit_chance_upgrade',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='player',
            name='crit_multiplier_upgrade',
            field=models.IntegerField(default=20),
        ),
    ]
