# Generated by Django 6.0.4 on 2026-04-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_crit_chance_upgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='auto_upgrade_cost',
            field=models.IntegerField(default=20),
        ),
    ]
