# Generated by Django 6.0.4 on 2026-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_auto_upgrade_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='crit_chance',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='crit_multiplier',
            field=models.IntegerField(default=2),
        ),
    ]
