# Generated by Django 6.0.4 on 2026-06-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_crit_chance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='crit_chance_upgrade',
            new_name='crit_chance_upgrade_cost',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='crit_multiplier_upgrade',
            new_name='crit_multiplier_upgrade_cost',
        ),
    ]
