# Generated by Django 6.0.4 on 2026-06-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_crit_chance_upgrade_player_crit_chance_upgrade_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_click',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
