# Generated by Django 6.0.4 on 2026-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_player_bow_per_click_player_crossbow_per_click_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_hp', models.IntegerField(default=1000)),
                ('boss_level', models.IntegerField(default=1)),
                ('boss_reward', models.IntegerField(default=500)),
                ('boss_next_spawn', models.DateTimeField(blank=True, null=True)),
                ('boss_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='player_level',
            field=models.IntegerField(default=0),
        ),
    ]
