# Generated by Django 6.0.4 on 2026-06-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_boss_player_player_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='luck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_luck_cost',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_luck_level',
            field=models.IntegerField(default=0),
        ),
    ]
