# Generated by Django 6.0.4 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_player_luck_player_upgrade_luck_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_max_hp', models.IntegerField(default=50)),
                ('monster_hp', models.IntegerField(default=50)),
                ('monster_name', models.CharField(default='Monster', max_length=50)),
                ('monster_reward', models.IntegerField(default=10)),
                ('monster_is_alive', models.BooleanField(default=True)),
                ('monster_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='boss',
            name='boss_active',
        ),
        migrations.AddField(
            model_name='boss',
            name='boss_max_hp',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='boss',
            name='boss_name',
            field=models.CharField(default='Boss', max_length=50),
        ),
        migrations.AddField(
            model_name='boss',
            name='killed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boss',
            name='spawned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boss',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('dead', 'Dead')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='time_offline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_time_offline_cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_time_offline_level',
            field=models.IntegerField(default=0),
        ),
    ]
