# Generated by Django 6.0.4 on 2026-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_monster_remove_boss_boss_active_boss_boss_max_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shekel_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_shekel_multiplier_cost',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_shekel_multiplier_level',
            field=models.IntegerField(default=0),
        ),
    ]
