# Generated by Django 6.0.4 on 2026-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_shekel_multiplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='upgrade_shekel_multiplier_cost',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_time_offline_cost',
            field=models.IntegerField(default=300),
        ),
    ]
