# Generated by Django 6.0.4 on 2026-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_player_upgrade_shekel_multiplier_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='crit_chance_upgrade_cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='crit_multiplier_upgrade_cost',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_luck_cost',
            field=models.IntegerField(default=200),
        ),
    ]
