# Generated by Django 6.0.4 on 2026-06-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_archer_per_second_player_architect_per_second_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='upgrade_darcher_level',
            new_name='upgrade_archer_level',
        ),
    ]
