# Generated by Django 6.0.4 on 2026-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_player_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_rebirth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_rebirth_cost',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='player',
            name='shekel_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
