# Generated by Django 6.0.4 on 2026-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_player_player_rebirth_player_player_rebirth_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_per_click',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_per_second',
            field=models.FloatField(default=0.0),
        ),
    ]
