# Generated by Django 6.0.4 on 2026-06-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_player_points_alter_player_points_per_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_per_click',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_per_second',
            field=models.IntegerField(default=0),
        ),
    ]
