# Generated by Django 6.0.4 on 2026-06-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_player_points_alter_player_points_per_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shekel_multiplier',
            field=models.FloatField(default=10.0),
        ),
    ]
