# Generated by Django 6.0.4 on 2026-06-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_player_shekel_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shekel_multiplier',
            field=models.IntegerField(default=10),
        ),
    ]
