# Generated by Django 6.0.4 on 2026-06-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_player_shekel_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_total_both_earned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_total_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_total_clicks_earned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_total_crits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_total_crits_earned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_total_passive_earned',
            field=models.BigIntegerField(default=0),
        ),
    ]
