# Generated by Django 6.0.4 on 2026-06-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_player_player_total_both_earned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_total_passive_earned',
        ),
    ]
