# Generated by Django 6.0.4 on 2026-06-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_rename_player_rebirth_player_rebirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rebirth_gems',
            field=models.FloatField(default=0.0),
        ),
    ]
