# Generated by Django 6.0.4 on 2026-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_player_rebirth_gems'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='anchor',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='player',
            name='dragon_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_anchor_cost',
            field=models.FloatField(default=3000.0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_anchor_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_dragon_multiplier_cost',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_dragon_multiplier_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_tax_cost',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name='player',
            name='upgrade_tax_level',
            field=models.IntegerField(default=1),
        ),
    ]
