# Generated by Django 6.0.4 on 2026-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_player_anchor_player_dragon_multiplier_player_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='upgrade_anchor_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_dragon_multiplier_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='upgrade_tax_level',
            field=models.IntegerField(default=0),
        ),
    ]
