# Generated by Django 6.0.4 on 2026-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_player_upgrade_anchor_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='anchor_click',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='player',
            name='anchor',
            field=models.FloatField(default=1000.0),
        ),
    ]
