# Generated by Django 6.0.4 on 2026-06-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_player_anchor_click_alter_player_anchor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='anchor_click',
            field=models.IntegerField(default=10),
        ),
    ]
